# Copyright (c) 2022 The ZMK Contributors
# SPDX-License-Identifier: MIT

CONFIG_LOG=y
CONFIG_ZMK_LOG_LEVEL_DBG=y

CONFIG_ZMK_BLE_PASSKEY_ENTRY=n

# Uncomment for Single color backlight
# CONFIG_ZMK_BACKLIGHT=y

# Uncomment for RGB
# CONFIG_ZMK_RGB_UNDERGLOW=y

# Uncomment for Display
CONFIG_ZMK_DISPLAY=y

CONFIG_ZMK_WIDGET_OUTPUT_STATUS=y
CONFIG_ZMK_WIDGET_LAYER_STATUS=y
CONFIG_ZMK_WIDGET_BATTERY_STATUS=y

CONFIG_LVGL_HOR_RES_MAX=128
CONFIG_LVGL_VER_RES_MAX=32
CONFIG_LVGL_VDB_SIZE=64
CONFIG_LVGL_DPI=148
CONFIG_LVGL_BITS_PER_PIXEL=1
CONFIG_LVGL_COLOR_DEPTH_1=y

# Uncomment these two lines to enable encoder support
# CONFIG_EC11=y
# CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y
